version: '3'

services:
  project:
    container_name: Investment-Standardization
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    environment:
      - DATABASE_URL=sqlite:////code/db.sqlite3
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND = 'django-db'
      -  CELERY_RESULT_PERSISTENT = True

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
