# Generated by Django 4.2.9 on 2024-01-16 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Operators",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("transaction_type", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "identifier",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("issue_date", models.DateField(blank=True)),
                ("maturity_date", models.DateField(blank=True)),
                (
                    "invested_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                ("debitor_identifier", models.CharField(blank=True, max_length=50)),
                ("seller_identifier", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name_plural": "Trades",
            },
        ),
        migrations.CreateModel(
            name="Cash_flows",
            fields=[
                (
                    "platform_transaction_id",
                    models.CharField(max_length=75, primary_key=True, serialize=False),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timestamp", models.DateField()),
                (
                    "operation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="cardo.operators",
                    ),
                ),
                (
                    "trade",
                    models.ForeignKey(
                        db_column="trade_identifier",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cashflows",
                        to="cardo.trade",
                    ),
                ),
            ],
        ),
    ]
