# Generated by Django 4.2.9 on 2024-01-16 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Operators",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("transaction_type", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
            ],
            options={
                "verbose_name_plural": "Trades",
            },
        ),
        migrations.CreateModel(
            name="Cash_flows",
            fields=[
                (
                    "cashflow_id",
                    models.CharField(max_length=75, primary_key=True, serialize=False),
                ),
                ("cashflow_date", models.DateField()),
                ("cashflow_currency", models.CharField(max_length=10)),
                ("cashflow_type", models.CharField(max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "trade",
                    models.ForeignKey(
                        db_column="trade_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cashflows",
                        to="cardo.trade",
                    ),
                ),
            ],
        ),
    ]
