# Generated by Django 4.2.9 on 2024-01-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardoTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('issue_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('invested_amount', models.FloatField()),
                ('debtor_identifier', models.CharField(max_length=255)),
                ('seller_identifier', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CardoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('trade_identifier', models.CharField(max_length=255)),
                ('platform_transaction_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_column', models.CharField(max_length=255)),
                ('standardized_column', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=255)),
            ],
        ),
    ]
