# Generated by Django 4.2.9 on 2024-01-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnmapping',
            name='raw_column',
            field=models.CharField(choices=[], max_length=255),
        ),
        migrations.AlterField(
            model_name='columnmapping',
            name='standardized_column',
            field=models.CharField(choices=[], max_length=255),
        ),
    ]
