# Generated by Django 4.2.9 on 2024-01-18 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cardo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cash_flows",
            old_name="trade",
            new_name="trade_identifier",
        ),
    ]
