# Generated by Django 4.2.9 on 2024-01-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="invested_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trade",
            name="maturity_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
