# Generated by Django 4.2.9 on 2024-01-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trade",
            name="data",
        ),
        migrations.AddField(
            model_name="trade",
            name="approved_limit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="closing_date",
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="company_bankrupted_date",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="company_bankrupted_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="currency",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="current_rating",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="day_count_convention",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="days_in_delay",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="debtor_identifier",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="default_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="default_date",
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="expected_net_return",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="extension_date",
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="interest_rate_exp",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="investment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="issue_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="loan_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="maturity_date",
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="outstanding_principal_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="performance_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="purchase_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="purchase_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="rating_source",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="related_parties",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="repurchased",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="rollovered_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="rollovered_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="rollovered_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="seller_identifier",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="trade_receivable_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="trade_receivable_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="write_off_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="write_off_date",
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
