# Generated by Django 4.2.9 on 2024-01-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardo', '0002_alter_columnmapping_raw_column_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='raw_data/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawDataMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data_model', models.CharField(max_length=255)),
                ('column_name', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='ColumnMapping',
        ),
        migrations.RemoveField(
            model_name='cardotrade',
            name='id',
        ),
        migrations.AlterField(
            model_name='cardotrade',
            name='debtor_identifier',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='cardotrade',
            name='identifier',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cardotrade',
            name='invested_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='cardotrade',
            name='seller_identifier',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='cardotransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='cardotransaction',
            name='platform_transaction_id',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='cardotransaction',
            name='trade_identifier',
            field=models.UUIDField(),
        ),
    ]
