# Generated by Django 4.2.9 on 2024-01-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cardo", "0002_alter_trade_invested_amount_alter_trade_issue_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trade",
            old_name="debitor_identifier",
            new_name="debtor_identifier",
        ),
    ]
