# Generated by Django 4.2.9 on 2024-01-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardo", "0002_remove_trade_data_trade_approved_limit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="issue_date",
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
