# Generated by Django 4.2.9 on 2024-01-16 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardo', '0003_rename_debitor_identifier_trade_debtor_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash_flows',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='cardo.operators'),
        ),
    ]
