# Generated by Django 4.2.9 on 2024-01-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="interest_rate",
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name="trade",
            name="invested_amount",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="issue_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
