# Generated by Django 4.2.9 on 2024-01-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='identifier',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
