# Generated by Django 4.2.9 on 2024-01-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0003_alter_trade_maturity_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="interest_rate",
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name="trade",
            name="invested_amount",
            field=models.DecimalField(
                blank=True, decimal_places=20, max_digits=30, null=True
            ),
        ),
    ]
