# Generated by Django 4.2.9 on 2024-02-20 12:40

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_identifier', models.CharField(max_length=400, unique=True)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='./Investment_Management/uploads/'), upload_to='')),
                ('file_name', models.CharField(max_length=400)),
            ],
        ),
    ]
