# Generated by Django 4.2.9 on 2024-02-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawdata",
            name="file_title",
            field=models.CharField(max_length=255),
        ),
    ]
