# Generated by Django 4.2.9 on 2024-02-06 15:46

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_rawdata_file_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawdata",
            name="file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="../uploads/"
                ),
                upload_to="",
            ),
        ),
    ]
