# Generated by Django 4.2.9 on 2024-02-06 16:19

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_alter_rawdata_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawdata",
            name="file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="C:\\Users\\Leonit\\OneDrive\\Desktop\\Investment_Management\\uploads"
                ),
                upload_to="",
            ),
        ),
    ]
