# Generated by Django 4.2.9 on 2024-02-12 08:48

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_alter_rawdata_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawdata",
            name="file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="./uploads/"
                ),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="file_title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
