# Generated by Django 4.2.9 on 2024-02-13 14:45

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_alter_rawdata_file_alter_rawdata_file_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_identifier", models.CharField(max_length=400, unique=True)),
                (
                    "file",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location="./uploads/"
                        ),
                        upload_to="",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="RawData",
        ),
    ]
