# Generated by Django 4.2.9 on 2024-02-15 10:38

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_file_delete_rawdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="./Investment_Management/uploads/"
                ),
                upload_to="",
            ),
        ),
    ]
