# Generated by Django 4.2.9 on 2024-02-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_alter_file_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file_name",
            field=models.CharField(default=None, max_length=400),
            preserve_default=False,
        ),
    ]
